import { createElement } from 'react';
import { Contrast, ArrowLeft, ArrowRight, ExternalLink, Award, Zap, Bookmark, Archive, BrainCircuit, BriefcaseBusiness, ChartLine, Check, CircleCheck, ChevronUp, CircleAlert, Info, CircleX, History, CloudUpload, Code2, Crown, Boxes, Download, Mail, Eraser, Eye, Film, Save, Gamepad2, GripVertical, Headphones, Heart, House, Image, Languages, Laptop, Layers, Lightbulb, Link2, MessageSquare, Send, PenTool, Play, Plug, CirclePlus, Rocket, RotateCw, Search, ZoomIn, Shapes, LoaderCircle, Star, X, Wrench, User, Users, UserRound, Volume2, Sparkles } from 'lucide-react';
import { FaGithub, FaLinkedin, FaInstagram, FaSpotify, FaDiscord, FaFigma } from 'react-icons/fa';
import { SiReact, SiKotlin, SiFirebase, SiFlutter, SiDart, SiJavascript, SiHtml5, SiCss3, SiPython, SiNodedotjs, SiMysql, SiGit, SiGithub, SiDocker, SiAndroidstudio, SiVite, SiTailwindcss, SiPhp, SiUnity, SiBootstrap, SiIntellijidea, SiFigma, SiTensorflow, SiScikitlearn, SiPandas, SiNetlify, SiOpencv } from 'react-icons/si';
const glyphs = { "fa-adjust": Contrast, "fa-arrow-left": ArrowLeft, "fa-arrow-right": ArrowRight, "fa-arrow-up-right-from-square": ExternalLink, "fa-award": Award, "fa-bolt": Zap, "fa-bookmark": Bookmark, "fa-box-archive": Archive, "fa-brain": BrainCircuit, "fa-briefcase": BriefcaseBusiness, "fa-certificate": Award, "fa-chart-line": ChartLine, "fa-check": Check, "fa-check-circle": CircleCheck, "fa-chevron-up": ChevronUp, "fa-circle-exclamation": CircleAlert, "fa-circle-info": Info, "fa-circle-xmark": CircleX, "fa-clock-rotate-left": History, "fa-cloud-arrow-up": CloudUpload, "fa-code": Code2, "fa-crown": Crown, "fa-cubes": Boxes, "fa-download": Download, "fa-envelope": Mail, "fa-eraser": Eraser, "fa-exclamation-circle": CircleAlert, "fa-external-link-alt": ExternalLink, "fa-eye": Eye, "fa-film": Film, "fa-floppy-disk": Save, "fa-gamepad": Gamepad2, "fa-grip-vertical": GripVertical, "fa-headphones": Headphones, "fa-heart": Heart, "fa-home": House, "fa-image": Image, "fa-language": Languages, "fa-laptop-code": Laptop, "fa-layer-group": Layers, "fa-lightbulb": Lightbulb, "fa-link": Link2, "fa-message": MessageSquare, "fa-paper-plane": Send, "fa-pen-nib": PenTool, "fa-play": Play, "fa-plug": Plug, "fa-plus-circle": CirclePlus, "fa-rocket": Rocket, "fa-rotate-right": RotateCw, "fa-search": Search, "fa-search-plus": ZoomIn, "fa-shapes": Shapes, "fa-spinner": LoaderCircle, "fa-star": Star, "fa-times": X, "fa-tools": Wrench, "fa-up-right-from-square": ExternalLink, "fa-user": User, "fa-users": Users, "fa-user-tie": UserRound, "fa-volume-high": Volume2, "fa-wand-magic-sparkles": Sparkles, "fa-wrench": Wrench, "fa-xmark": X, "fa-github": FaGithub, "fa-linkedin": FaLinkedin, "fa-instagram": FaInstagram, "fa-spotify": FaSpotify, "fa-discord": FaDiscord, "fa-figma": FaFigma };
const technologies = { "react": SiReact, "kotlin": SiKotlin, "firebase": SiFirebase, "flutter": SiFlutter, "dart": SiDart, "javascript": SiJavascript, "html5": SiHtml5, "css3": SiCss3, "python": SiPython, "nodejs": SiNodedotjs, "mysql": SiMysql, "git": SiGit, "github": SiGithub, "docker": SiDocker, "androidstudio": SiAndroidstudio, "vitejs": SiVite, "tailwindcss": SiTailwindcss, "php": SiPhp, "unity": SiUnity, "bootstrap": SiBootstrap, "intellij": SiIntellijidea, "figma": SiFigma, "tensorflow": SiTensorflow, "scikitlearn": SiScikitlearn, "pandas": SiPandas, "netlify": SiNetlify, "opencv": SiOpencv };
export default function Icon({ className = '', style, title, 'aria-label': label }) {
 const tokens = className.split(/\s+/);
 const technology = tokens.find(token => token.startsWith('devicon-'))?.split('-')[1];
 const component = tokens.map(token => glyphs[token]).find(Boolean) || technologies[technology] || Code2;
 return createElement(component, { size: '1em', className: className + (tokens.includes('fa-spin') ? ' animate-spin' : ''), style: { display: 'inline-block', verticalAlign: '-0.125em', ...style }, title, 'aria-hidden': label ? undefined : true, 'aria-label': label });
}
